# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20171114_1122'),
        ('chat', '0001_initial'),
    ]

    operations = [
        
    ]
