# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20171114_1122'),
        ('chat', '0002_auto_20171113_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='question',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Question'),
        ),
    ]
