# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(choices=[('BV', 'Bovino'), ('PR', 'Porcino'), ('EQ', 'Equino'), ('OV', 'Ovino'), ('GL', 'Gallus'), ('LP', 'Leporido'), ('AV', 'Ave'), ('CN', 'Canino'), ('FL', 'Felino'), ('SL', 'Silvestre')], default='', max_length=3)),
                ('question', models.CharField(default='', max_length=100)),
                ('info', models.TextField(blank=True, default='', null=True)),
                ('age', models.CharField(default=0, max_length=2)),
                ('weight', models.CharField(default=0, max_length=10)),
                ('gender', models.CharField(choices=[('ML', 'Macho'), ('FM', 'Hembra')], default='ML', max_length=3)),
                ('Physiological_state', models.CharField(choices=[('LC', 'Lactante'), ('PG', 'Gestante'), ('IC', 'Crecimiento')], default='LC', max_length=3)),
                ('reason', models.CharField(default='', max_length=100)),
                ('lpm', models.CharField(default=0, max_length=10)),
                ('rpm', models.CharField(default=0, max_length=10)),
                ('temperature', models.CharField(default=0, max_length=3)),
                ('capillary_filling_time', models.CharField(default='', max_length=100)),
                ('mucous_Coloring', models.CharField(default='', max_length=100)),
                ('lymph_nodes', models.CharField(default='', max_length=100)),
                ('clinic_history', models.TextField(blank=True, default='', null=True)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions')),
            ],
        ),
    ]
