# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='lpm',
            new_name='cardiaco',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='clinic_history',
            new_name='clinica',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='age',
            new_name='edad',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='species',
            new_name='especie',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Physiological_state',
            new_name='fisiologico',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='info',
            new_name='informacion',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='capillary_filling_time',
            new_name='linfonodos',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='lymph_nodes',
            new_name='llenado',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='mucous_Coloring',
            new_name='motivo',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='mucosas',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='rpm',
            new_name='peso',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='reason',
            new_name='pregunta',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='weight',
            new_name='respiratorio',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='gender',
            new_name='sexo',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='temperature',
            new_name='temperatura',
        ),
    ]
